services:
  server:
    build:
      context: ./server
    container_name: aliconcon-ecommerce-server
    ports:
      - "127.0.0.1:3002:3002"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - path: ./.env
        required: false
    environment:
      - NODE_ENV=${NODE_ENV}
      - HOST=${HOST}
      - PORT=${PORT}
      - CLIENT_URL=${CLIENT_URL}
      - ACCESS_TOKEN_EXPIRED_TIME=${ACCESS_TOKEN_EXPIRED_TIME}
      - REFRESH_TOKEN_EXPIRED_TIME=${REFRESH_TOKEN_EXPIRED_TIME}
      
      # Google mail service
      - OAUTH2_USER=${OAUTH2_USER}
      - OAUTH2_ACCESS_TOKEN=${OAUTH2_ACCESS_TOKEN}
      - OAUTH2_REFRESH_TOKEN=${OAUTH2_REFRESH_TOKEN}
      - OAUTH2_CLIENT_ID=${OAUTH2_CLIENT_ID}
      - OAUTH2_CLIENT_SECRET=${OAUTH2_CLIENT_SECRET}
      - OAUTH2_CALLBACK_URL=${OAUTH2_CALLBACK_URL}

      # VNPay
      - VNPAY_TMN_CODE=${VNPAY_TMN_CODE}
      - VNPAY_HASH_SECRET=${VNPAY_HASH_SECRET}
      - VNPAY_URL=${VNPAY_URL}
      - VNPAY_RETURN_URL=${VNPAY_RETURN_URL}
      - VNPAY_IPN_URL=${VNPAY_IPN_URL}
      - VNPAY_API_URL=${VNPAY_API_URL}

      - MCP_SERVER_PORT=8081
      - MCP_CLIENT_PORT=8080

      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

      # MongoDB
      - MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DB_NAME}?authSource=admin

      # OpenRouteService
      - OPEN_ROUTE_SERVICE_API_KEY=${OPEN_ROUTE_SERVICE_API_KEY}
    depends_on:
      - mongodb
      - redis
    networks:
      - aliconcon-network

  client-mcp:
    build:
      context: ./mcp/client
    container_name: aliconcon-ecommerce-client-mcp
    ports:
      - "8080:8080"
    volumes:
      - ./mcp/client:/app
      - /app/node_modules
    environment:
      - PORT=8080
      - WEBSOCKET_PORT=8080
      - MCP_URL=http://server-mcp:8081
      - USE_WSS=false
    networks:
      - aliconcon-network

  server-mcp:
    build:
      context: ./mcp/server
    container_name: aliconcon-ecommerce-server-mcp
    ports:
      - "8081:8081"
    volumes:
      - ./mcp/server:/app
      - /app/node_modules
    environment:
      - MCP_PORT=8081
    networks:
      - aliconcon-network

  mongodb:
    image: mongo:latest
    container_name: aliconcon-ecommerce-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    volumes:
      - mongodb_data:/data/db
    networks:
      - aliconcon-network

  redis:
    image: redis:alpine
    container_name: aliconcon-ecommerce-redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:6379" # not change config
    volumes:
      - redis_data:/data
    networks:
      - aliconcon-network

networks:
  aliconcon-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
