services:
  server:
    build:
      context: ./server
    container_name: aliconcon-ecommerce-server
    ports:
      - "127.0.0.1:3003:3003"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./.env
      - ./server/.env.${NODE_ENV}.local
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DB_NAME}?authSource=admin
      - REDIS_URL=redis://${REDIS_USER}:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
    depends_on:
      - mongodb
      - redis
    networks:
      - aliconcon-network

  client-mcp:
    build:
      context: ./mcp/client
    container_name: aliconcon-ecommerce-client-mcp
    env_file:
      - mcp/client/.env.${NODE_ENV}.local
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - NODE_ENV=${NODE_ENV}
      - WEBSOCKET_PORT=8080
      - MCP_URL=http://server-mcp:8081
      - REDIS_URL=redis://${REDIS_USER}:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
    depends_on:
      - server-mcp
    networks:
      - aliconcon-network

  server-mcp:
    build:
      context: ./mcp/server
    container_name: aliconcon-ecommerce-server-mcp
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MCP_PORT=8081
      - API_BASE_URL=http://server:3003
    networks:
      - aliconcon-network

  mongodb:
    image: mongo:latest
    container_name: aliconcon-ecommerce-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    volumes:
      - mongodb_data:/data/db
    networks:
      - aliconcon-network

  redis:
    image: redis:alpine
    container_name: aliconcon-ecommerce-redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:6379" # not change config
    volumes:
      - redis_data:/data
    networks:
      - aliconcon-network

networks:
  aliconcon-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
